# Generated by Django 5.2 on 2026-01-23 08:55

import app1.models
import app1.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_service_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, storage=app1.storage.OverwriteStorage(), upload_to=app1.models.upload_image_path),
        ),
    ]
