# Generated by Django 5.2 on 2026-01-23 08:59

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_service_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.upload_image_path),
        ),
    ]
